#variables:
#  GIT_STRATEGY: clone
#  user: cloud_use
#default:
#  before_script:
#    - rm /root/.ssh/known_hosts
#    - touch /root/.ssh/known_hosts
#    - apk add sshpass 
.only-develop:
  only:
   - develop
.only-milestone:
  only:
   - milestone*
stages:
 - deploy-to-prod
 - deploy-to-stag
to-prod:
 extends: .only-develop
 stage: deploy-to-prod
 script: 
  - pwd
  - ls -la
  - cd ../
  - pwd
  - sudo rm -rf /var/www/html/chicstays-backend
  - ls -la /var/www/html
  - sudo cp -r chicstays-backend/ /var/www/html/chicstays-backend
  - ls -la /var/www/html/chicstays-backend
  - cd /var/www/html/chicstays-backend
  - pwd
  - composer install
  - cp ~/.env .env
  - ls -la /var/www/html/chicstays-backend
 tags:
  - prod
 rules:
  - if: '$CI_COMMIT_BRANCH == "develop"'
 artifacts:
   paths:
     - results.log
   expire_in: 2 week

# 

to-stag:
 extends: .only-milestone
 stage: deploy-to-stag
 script: 
  - pwd
  - ls -la
  - cd ../
  - pwd
  - sudo rm -rf /var/www/html/chicstays-backend
  - ls -la /var/www/html
  - sudo cp -r chicstays-backend/ /var/www/html/chicstays-backend
  - ls -la /var/www/html/chicstays-backend
  - cd /var/www/html/chicstays-backend
  - pwd
  - composer install
  - cp ~/.env .env
  - ls -la /var/www/html/chicstays-backend
 tags:
  - stag
 rules:
  - if: '$CI_COMMIT_BRANCH =~ "milestone*"'
 artifacts:
   paths:
     - results.log
   expire_in: 2 week  
