#variables:
#  GIT_STRATEGY: clone
#  user: cloud_use
#default:
#  before_script:
#    - rm /root/.ssh/known_hosts
#    - touch /root/.ssh/known_hosts
#    - apk add sshpass 
.only-develop:
  only:
   - develop
stages:
 - deploy
running-main-pipeline-script-to-deploy-everything:
 extends: .only-develop
 stage: deploy
 script: 
  - pwd
  - ls -la
  - cd ../
  - pwd
  - sudo rm -rf /var/www/html/chicstays-backend
  - ls -la /var/www/html/chicstays-backend
  - sudo cp -r chicstays-backend/ /var/www/html/chicstays-backend
  - ls -la /var/www/html/chicstays-backend
  - cd /var/www/html/chicstays-backend
  - pwd
  - composer install
  - cp ~/.env .env
  - ls -la /var/www/html/chicstays-backend
 artifacts:
   paths:
     - results.log
   expire_in: 2 week  
